volumes:
  llamacpp:

services:
  llamacpp-gemma:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    command: -hf ggml-org/gemma-4-E2B-it-GGUF
    ports:
      - "8001:8080"
    # environment:
    #   - LLAMA_ARG_N_GPU_LAYERS=999
    volumes:
      - /mnt/data/workspace/local-llm-server/llama-cpp:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

